// This file is auto-generated. Do not edit manually.
const { version } = require("../../package.json");
const fs = require("fs");

const buildTime = new Date().toISOString();

const content = `// This file is auto-generated by scripts/gen-version.js
export const VERSION = "${version}";
export const BUILD_TIME = "${buildTime}";
`;

fs.writeFileSync(__dirname + "/../version.ts", content);
console.log("src/version.ts generated:", content);
